name: Headstones
description: Don't lose your precious items when you die!
authors: [ alex3025 ]
website: https://alex3025.tk

version: '${project.version}'
api-version: 1.18
main: tk.alex3025.headstones.Headstones

commands:
  headstones:
    aliases: [ hs, headstone ]
    usage: /headstones
